name: Build EXE

on:
  push:
    branches:
      - master  # Triggers build on push to the master branch
  pull_request:
    branches:
      - master
        
env:
  RELEASE_VERSION: v1.0.0  # Define the version here

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x # Specify the .NET version you're using

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build and Publish a Portable EXE
      - name: Publish Portable EXE
        run: |
          dotnet publish -c Release -r win-x64 --self-contained true `
            "-p:PublishSingleFile=true" `
            "-p:IncludeNativeLibrariesForSelfExtract=true" `
            -o ./output

      # Step 5: Set up git authentication with the PAT token
      - name: Set up git authentication
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git config --global url."https://${{ secrets.PAT_TOKEN }}@github.com".insteadOf "https://github.com"

      # Step 6: Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: SchwabCSVReader ${{ env.RELEASE_VERSION }}
          body: |
            This is an automated release for SchwabCSVReader.
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use the PAT_TOKEN secret for release creation

      # Step 7: Upload EXE to Release
      - name: Upload EXE to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/SchwabCSVReader.exe
          asset_name: SchwabCSVReader.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use the PAT_TOKEN secret for asset upload