name: Build EXE

on:
  push:
    branches:
      - master  # Triggers build on push to the master branch
  pull_request:
    branches:
      - master
        
env:
  RELEASE_VERSION: v1.0.0  # Define the version here

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x # Specify the .NET version you're using

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build and Publish a Portable EXE
      - name: Publish Portable EXE
        run: |
          dotnet publish -c Release -r win-x64 --self-contained true `
            "-p:PublishSingleFile=true" `
            "-p:IncludeNativeLibrariesForSelfExtract=true" `
            -o ./output

      # Step 5: Delete Existing Release (if exists)
      - name: Delete Existing Release and Tag
        run: |
          # Delete the release if it exists
          gh release delete ${{ env.RELEASE_VERSION }} --yes || echo "No existing release to delete"

          # Delete the tag if it exists
          git tag -d ${{ env.RELEASE_VERSION }} || echo "No existing local tag to delete"
          git push origin --delete ${{ env.RELEASE_VERSION }} || echo "No existing remote tag to delete"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Create a New Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: SchwabCSVReader ${{ env.RELEASE_VERSION }}
          body: |
            This is an release for SchwabCSVReader.
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 7: Upload the EXE to the Release
      - name: Upload EXE to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/SchwabCSVReader.exe
          asset_name: SchwabCSVReader.exe
          asset_content_type: application/octet-stream
