name: Build EXE

on:
  push:
    branches:
      - master  # Triggers build on push to the master branch
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x # Specify the .NET version you're using

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build project
        run: dotnet build --configuration Release

      # Step 5: Publish the EXE
      - name: Publish EXE
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:PublishTrimmed=true -o ./output


      # Step 6: Upload the EXE as an artifact
      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: CombinedCSVReaderExe
          path: ./output/*
